"""users

Revision ID: 4ef29d5a8983
Revises: 
Create Date: 2024-04-19 01:56:14.001864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef29d5a8983'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('relevant_skills', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('desired_job_role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('resume', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=100), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('username')
        batch_op.drop_column('verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('resume')
        batch_op.drop_column('desired_job_role')
        batch_op.drop_column('profession')
        batch_op.drop_column('relevant_skills')
        batch_op.drop_column('education')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
